### ISSUE TITLE
New Architecture Support

### ISSUE THREAD

**Issue by okwasniewski** [okwasniewski/react-native-bottom-tabs#10]
Goal of this issue is to track new architecture support for Native Bottom Tabs.

**Comment by shovel-kun** [comment]
Currently, prebuilds on new arch fails with unresolved references of `SwiftuiTabviewViewManagerInterface` and `SwiftuiTabviewViewManagerDelegate`

**Comment by CodeWithShreyans** [comment]
New Arch is gonna be stabilized soon, any updates on this?

**Comment by okwasniewski** [comment]
@CodeWithShreyans Just started to work on it you can track the progress in #64
