### ISSUE TITLE
crash when stress testing tab change

### ISSUE THREAD

**Issue by gunnartorfis** [okwasniewski/react-native-bottom-tabs#117]
When I change between tabs at an abnormal speed, the app eventually crashes.

It is a Release variant on iOS and I haven't got Sentry source maps set up without EAS build/update, but here's what I got on Sentry:

<img width="761" alt="Screenshot 2024-11-03 at 13 55 03" src="https://github.com/user-attachments/assets/5473b15f-393c-42b8-8b3a-bbc3497157c2">

https://github.com/user-attachments/assets/61e63e56-f087-4a03-a0ea-ff8155038092

**Comment by okwasniewski** [comment]
Hey, would you mind sharing a stack trace? 

Without it's going to be extremely difficult. I tested it in the example app in the repo and it's not happening.

Maybe it's something within your app that causes this

**Comment by gunnartorfis** [comment]
Not sure if there's something else you'd want from Xcode, let me know if this isn't sufficient

<img width="726" alt="Screenshot 2024-11-03 at 14 08 53" src="https://github.com/user-attachments/assets/3232f22a-86ea-46e5-8cee-748b7356cc8d">

<img width="1507" alt="Screenshot 2024-11-03 at 14 09 15" src="https://github.com/user-attachments/assets/9879b507-5cc9-4d54-9d66-6af337a94810">

**Comment by okwasniewski** [comment]
Thanks this is helpful, judging by the stack trace you are using new architecture?

**Comment by gunnartorfis** [comment]
Yep

**Comment by okwasniewski** [comment]
Can you re-test this with 0.3.1? 🙏

**Comment by gunnartorfis** [comment]
Wasn't able to reproduce this on 0.3.1 🥳
