### ISSUE TITLE
createNativeBottomTabNavigator creates truncated labels on iPadOS < 18 and iOS in landscape

### ISSUE THREAD

**Issue by johankasperi** [okwasniewski/react-native-bottom-tabs#124]
Thanks for an awesome library! This is a huge improvement for React Native.

When using `createNativeBottomTabNavigator` the labels are truncated on iPadOS < 18 and on iOS when in landscape. I can replicate this in the example project. The same bug is not present when using `TabView`. I'm using Xcode 16.1

### iPad 10th generation iPadOS 17.5 (Simulator)
![Simulator Screenshot - iPad (10th generation) - 2024-11-05 at 11 36 15](https://github.com/user-attachments/assets/347cfc39-7d38-4dc1-b1b6-8d3378d1c2d1)

### iPhone 16 Pro iOS 18.1 (Simulator)
![Simulator Screenshot - iPhone 16 Pro - 2024-11-05 at 11 40 43](https://github.com/user-attachments/assets/148a3104-276c-4241-a22e-2f1d4172082a)

I've tried to look into what is causing this but haven't found anything yet.

**Comment by johankasperi** [comment]
It's happening when I'm setting `tabBarInactiveTintColor` (can replicate the bug on `TabView` when setting this property) and it's because of this code https://github.com/okwasniewski/react-native-bottom-tabs/blob/e96c92c2dfe58b04e115e5877dcf24d9fd0cea03/ios/TabViewImpl.swift#L157

**Comment by okwasniewski** [comment]
Thanks for reporting the issue and doing the initial debugging! 

Weird that background color affects this 😅 I will look into this

**Comment by johankasperi** [comment]
Are you sure that we need to do the "hack" suggested in https://stackoverflow.com/a/71934882 ?

I've tested with this code and almost got everything working:
```swift
    UITabBar.appearance().barTintColor = props.barTintColor
    UITabBar.appearance().isTranslucent = props.translucent
    UITabBar.appearance().unselectedItemTintColor = props.inactiveColor
```

But to make that work we cannot override the appearance with:
```swift
  UITabBar.appearance().standardAppearance = appearance
```
so we have to remove that code

**Comment by okwasniewski** [comment]
I am not sure about this, maybe it's not needed. 

If you got it working can you open a PR? 🙏

**Comment by johankasperi** [comment]
> I am not sure about this, maybe it's not needed.
> 
> If you got it working can you open a PR? 🙏

Of course! I haven't got it working yet though but after some initial tests I believe we can get it working without that "hack" from Stackoverflow. I can give it a go asap and open a PR.
