### ISSUE TITLE
shifting label.

### ISSUE THREAD

**Issue by a-eid** [okwasniewski/react-native-bottom-tabs#128]
I am getting this weird behavior with one of the tabs, where it shifts a bit when clicked, also when clicked when active it shifts sometimes. 

![shifting-label](https://github.com/user-attachments/assets/f22ab5a3-5f0d-45aa-9f55-fa99f8a92114)

Edit: 

this seem to happen because label is too wide!

sometimes it just truncate the label, not always thou. 

<img width="195" alt="Screenshot 2024-11-08 at 12 14 38 AM" src="https://github.com/user-attachments/assets/c5c63fee-b71b-4c2c-ab29-629a380dc85b">

FYI( this happens when I remove the 's' & press on the tab once or twice ).

**Comment by okwasniewski** [comment]
Thanks for reporting the issue, looks like it's related to #124 I'm going to look into this

**Comment by okwasniewski** [comment]
This should be fixed in 0.5.0 when setting `scrollEdgeAppreance="transparent"`. Unfortunately it looks like when setting different apperance the items are jumping which is a bug in Tab View component. This can be reported as a bug for Apple 😢

**Comment by okwasniewski** [comment]
I'm going to close this as there is nothing we can do about SwiftUI bug
