### ISSUE TITLE
Handle more than 6 tabs

### ISSUE THREAD

**Issue by okwasniewski** [okwasniewski/react-native-bottom-tabs#13]
On Android more than 6 tabs cause a native error. 

Goal of this issue is to limit array of views passed to Android Bottom Navigation View to 6

**Comment by mrpmohiburrahman** [comment]
Hi, @okwasniewski,
I want to take a look at this issue.
( I am a newbie on open source contribution. )

**Comment by okwasniewski** [comment]
Sure @mrpmohiburrahman go ahead :) Let me know if you need any help

**Comment by mrpmohiburrahman** [comment]
> On Android more than 6 tabs cause a native error.
> Goal of this issue is to limit array of views passed to Android Bottom Navigation View to 6

I can see there is an implementation of throwing an error when the tabs are greater than 6. [here](https://github.com/mrpmohiburrahman/react-native-bottom-tabs/blob/main/src/TabView.tsx#L90).

How can we limit the array of views?
Should we put some kind of ts error/warning, so that when the views are greater then 6 then it will show a squiggly line?
Or show the first 6 of the views and avoid the rest?

**Comment by okwasniewski** [comment]
> > On Android more than 6 tabs cause a native error.
> 
> > Goal of this issue is to limit array of views passed to Android Bottom Navigation View to 6
> 
> 
> 
> I can see there is an implementation of throwing an error when the tabs are greater than 6. [here](https://github.com/mrpmohiburrahman/react-native-bottom-tabs/blob/main/src/TabView.tsx#L90).
> 
> 
> 
> How can we limit the array of views?
> 
> 
> 
> Should we put some kind of ts error/warning,
> 
> so that when the views are greater then 6 then it will show a squiggly line?
> 
> 
> 
> Or show the first 6 of the views and avoid the rest?

So the way I think it should work is:

1. Change the error to a warning
2. Limit the number of tabs (items) passed to TabView to 6.

You can achieve this using Array.splice

This will prevent users from getting crashes in production when dynamically adding tabs (should only show an error).

**Comment by mrpmohiburrahman** [comment]
Hi, @okwasniewski
I've made a pull request https://github.com/okwasniewski/react-native-bottom-tabs/pull/38.
Would greatly appreciate your feedback.
