### ISSUE TITLE
White screen issue with sidebarAdaptable

### ISSUE THREAD

**Issue by robertherber** [okwasniewski/react-native-bottom-tabs#130]
We have a whitescreen issue when using react-native-bottom-tabs with `sidebarAdaptable` enabled. Disabling sidebarAdaptable makes it work as expected. A bit weird since I guess sidebarAdaptable really only makes sense for tablets and bigger screens.

We use the latest version of Expo, expo router, react-native-bottom-tabs and React Native 0.74.

It happens on the following device:
- iPhone 16 Pro (device, with latest iOS 18.2 public beta)

The whitescreen issue was not seen on the following devices:
- iPhone 12 Pro (device, with iOS 17.6.1)
- iPhone 15 Plus (simulator, with iOS 17.5)
- iPad Air 13-inch (simulator, with iOS 17.5, although notably the sidebar didn't "adapt" here)

**Comment by okwasniewski** [comment]
Hey, thanks for opening the issue. 

The `sidebarAdaptable` prop is available only for iOS 18+, so `iPad Air 13-inch (simulator, with iOS 17.5)` didn't get it. 

Can you try it on a device without beta software? I will look into this

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the TabViewImpl struct to properly handle the sidebarAdaptable property on iOS 18 and above. This should fix the whitescreen issue on iPhone 16 Pro with iOS 18.2 public beta.

I also created pull request: https://github.com/okwasniewski/react-native-bottom-tabs/pull/131


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by robertherber** [comment]
> Hey, thanks for opening the issue.
> 
> The `sidebarAdaptable` prop is available only for iOS 18+, so `iPad Air 13-inch (simulator, with iOS 17.5)` didn't get it.
> 
> Can you try it on a device without beta software just to make sure its not something introduced by Apple? I will look into this

Thanks for the quick reply! I tested again on iOS 18.1 with the following simulators and got the same white screen behaviour:
- iPad Air 13-inch
- iPhone 16

**Comment by okwasniewski** [comment]
@robertherber I just checked and I'm unable to reproduce this on iPhone 15 Pro running on iOS 18.1 

Can you provide a minimal reproduction code?

**Comment by okwasniewski** [comment]
Oh no I can see the bug! 

```
#if compiler(>=6.0)
        self.tabViewStyle(.sidebarAdaptable)
#endif
```

You are running Xcode < 16, right?

**Comment by robertherber** [comment]
> Oh no I can see the bug!
> 
> ```
> #if compiler(>=6.0)
>         self.tabViewStyle(.sidebarAdaptable)
> #endif
> ```
> 
> You are running Xcode < 16, right?
> 
> Can you check if this diff fixes it?
> 
> ```diff
> diff --git a/ios/TabViewImpl.swift b/ios/TabViewImpl.swift
> index 244999f..8295d99 100644
> --- a/ios/TabViewImpl.swift
> +++ b/ios/TabViewImpl.swift
> @@ -222,6 +222,8 @@ extension View {
>        if (enabled) {
>  #if compiler(>=6.0)
>          self.tabViewStyle(.sidebarAdaptable)
> +#else
> +        self
>  #endif
>        } else {
>          self
> ```

Thanks for looking into it, quite possible this is the case! I'm on XCode 16.1 locally but we're running on Expo Dev Clients, so I guess it depends on what EAS is running.

**Comment by okwasniewski** [comment]
Can you try with 0.4.0?

https://github.com/okwasniewski/react-native-bottom-tabs/releases/tag/v0.4.0
