### ISSUE TITLE
Compatibility with `expo-image` on Android

### ISSUE THREAD

**Issue by okwasniewski** [okwasniewski/react-native-bottom-tabs#141]
Currently due to both libraries using Glide (native dependency) and including their own AppGlideModule its not possible to use them together. 

To solve this we need to probably remove AppGlideModule from both Bottom Tabs and Expo Image and generate this file (one per project). 

Goal of this issue is to track the compatibility.

**Comment by ajanuar** [comment]
Hi @okwasniewski , I've tested 0.5.1 and still facing this issue.

```
Type com.bumptech.glide.GeneratedAppGlideModuleImpl is defined multiple times: /Users/pintu/Documents/pintu/pintu-react-native/packages/apps/node_modules/react-native-bottom-tabs/android/build/.transforms/307235aa7405415dc1e7321c93ad28a3/transformed/classes/classes_dex/classes.dex, /Users/pintu/Documents/pintu/pintu-react-native/packages/apps/node_modules/expo-image/android/build/.transforms/13f42b336286962acdd6a9a2e03e1e73/transformed/classes/classes_dex/classes.dex
```

**Comment by okwasniewski** [comment]
@ajanuar I'm trying to get in touch with Expo team to get this working, unfortunately it requires action on both expo image side and Bottom Tabs

**Comment by okwasniewski** [comment]
@ajanuar Can you check with 0.5.2?

**Comment by ajanuar** [comment]
@okwasniewski now it's working well. thanks!
