### ISSUE TITLE
SVGs don't work with TabBarIcon using it with expo router

### ISSUE THREAD

**Issue by boblitex** [okwasniewski/react-native-bottom-tabs#143]
while PNGs work as TabBarIcon, SVGs are blank as opposed to what's shown in the documentation ( for react navigation) but you get the idea

**Comment by okwasniewski** [comment]
Hey @boblitex can you provide a minimal reproduction? 

Here I have an example of using SVGs with bottom tabs: https://github.com/okwasniewski/ExpoNativeTabs 

Can you try if it works for you?

**Comment by okwasniewski** [comment]
Can you check with 0.5.2?

**Comment by Peek-A-Booo** [comment]
> Can you check with 0.5.2?

0.5.2 doesn't work for me. 
(only `sfSymbol` and `uri` working, `require` not)

```
<Tab.Screen
  name="Albums"
  component={Albums}
  options={{
    tabBarIcon: () => require('person.png'),
    // SVG is also supported
    tabBarIcon: () => require('person.svg'),
    // or
    tabBarIcon: () => ({ sfSymbol: 'person' }),
    // You can also pass a URL
    tabBarIcon: () => ({ uri: 'https://example.com/icon.png' }),
  }}
/>
```

**Comment by okwasniewski** [comment]
@Peek-A-Booo Can you share code snippet that doesn't work for you?

Just to be sure did you provide a full path? `tabBarIcon: () => require('../../assets/images/home-icon-silhouette.svg') `

**Comment by Peek-A-Booo** [comment]
@okwasniewski code&result with expo router

### Code
<img width="2051" alt="image" src="https://github.com/user-attachments/assets/fb1531e1-f108-4670-80ec-3c854f6d276f">

### Result
![image](https://github.com/user-attachments/assets/93fe03db-7a6c-47c6-9e87-ff1ed946c5ee)

**Comment by okwasniewski** [comment]
@Peek-A-Booo Thanks, and is it working for you on iOS?

**Comment by Peek-A-Booo** [comment]
@okwasniewski Thanks. For me, the only ones working in iOS are `sfSymbol` and `uri`.

Looks like

```
 tabBarIcon: () => ({ sfSymbol: 'person' }),

 tabBarIcon: () => ({ uri: 'https://example.com/icon.png' }),
```

**Comment by Peek-A-Booo** [comment]
@okwasniewski Found my mistake. I introduced `react-native-svg-transformer` to use SVG, and configured it like this:
https://github.com/kristerkari/react-native-svg-transformer?tab=readme-ov-file#step-3-configure-the-react-native-packager

```
const { getDefaultConfig } = require("expo/metro-config");

module.exports = (() => {
  const config = getDefaultConfig(__dirname);

  const { transformer, resolver } = config;

  config.transformer = {
    ...transformer,
    babelTransformerPath: require.resolve("react-native-svg-transformer/expo")
  };

  config.resolver = {
    ...resolver,
    assetExts: resolver.assetExts.filter((ext) => ext !== "svg"),
    sourceExts: [...resolver.sourceExts, "svg"]
  };

  return config;
})();
```

Commenting out `config.resolver = { xxx }` will make it correct. But this will prevent me from directly referencing SVG in the project. I will continue to solve my own problems. Thank you very much for your reminder.

**Comment by boblitex** [comment]
@okwasniewski maybe we should find a way around using the bottomTabs with `react-native-svg-transformer`, it's quite popular and I also have it in my metro config

**Comment by okwasniewski** [comment]
@boblitex 

I think that if you don't add this line `assetExts: assetExts.filter((ext) => ext !== "svg")` which removes svg's from assetExts both libraries should work together. Can you confirm?

**Comment by boblitex** [comment]
@okwasniewski 
![image](https://github.com/user-attachments/assets/97e5be4f-4462-44ba-a820-a8d9ec913173)
that's what I get when I try to use the svg transformer with the assetExts line removed

the SVGs in the bottomTabs work now though. so I'm trying to see
