### ISSUE TITLE
Add Example usage with react-native-vector-icons

### ISSUE THREAD

**Issue by okwasniewski** [okwasniewski/react-native-bottom-tabs#15]
React Native Vector Icons allow users to retrieve the source of the icon. 

Goal of this issue is to add new example & section in docs to outline how to use React native vector icons: 

```tsx
import Icon from 'react-native-vector-icons/Ionicons';

const navIcon = Icon.getImageSourceSync('md-arrow-back', 24, 'white');
const overflowIcon = Icon.getImageSourceSync('md-more', 24, 'white');
const settingsIcon = Icon.getImageSourceSync('md-settings', 30, 'white');
const twitterIcon = Icon.getImageSourceSync('logo-twitter', 25, '#4099FF');
```

**Comment by fredrikburmester** [comment]
How can I use [@expo/vector-icons](https://docs.expo.dev/guides/icons/#expovector-icons)?

**Comment by kevindetry** [comment]
@fredrikburmester since [`@expo/vector-icons` doesn't expose `getImageSourceSync`](https://github.com/expo/vector-icons/issues/26), it doesn't seem to be possible to use.
