### ISSUE TITLE
Handle more than 5 tabs on iOS

### ISSUE THREAD

**Issue by okwasniewski** [okwasniewski/react-native-bottom-tabs#16]
On iOS we get the "More" tab when user adds 5 tabs. 

This opens a new list with destinations we can navigate to, currently navigating with this list doesn't work with lazy loading as we don't get the event.

**Comment by cesargdm** [comment]
Hey @okwasniewski thanks for your work, would there be a way to customize that "More" tab? I'm free to explore the feature if you could point me to the right direction.

**Comment by okwasniewski** [comment]
Hey @cesargdm, 

What do you mean by customizing / what do you need to change? I think "More" tab appearance is strictly defined by the system which we can't change.
