### ISSUE TITLE
Tab.Navigator and Tab.Screen are typed as any

### ISSUE THREAD

**Issue by Nodonisko** [okwasniewski/react-native-bottom-tabs#176]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

Components are typed as `any`.

```
"@bottom-tabs/react-navigation": "^0.7.1",
"react-native-bottom-tabs": "^0.7.1",
"typescript": "5.5.4",
"@react-navigation/native": "6.1.18",
"@react-navigation/native-stack": "6.11.0",
```

### Library version

0.7.1

### Environment info

```shell
"react-native": "0.76.1",
"expo": "52.0.11",
"typescript": "5.5.4",
```
```


### Steps to reproduce

1. …
2. …


### Reproducible sample code

```js
import { createNativeBottomTabNavigator } from '@bottom-tabs/react-navigation';

const Tab = createNativeBottomTabNavigator();

// this will not throw or autocomplete because it's typed as any
<Tab.Navigator {...props} nonExistingProp="hello" />
// same goes for 
<Tab.Screen {...props} nonExistingProp="hello" />
```

**Comment by Nodonisko** [comment]
I am thinking could this be related to that we use `react-navigation` v6? It seems there is lot of error in file `src/navigators/createNativeBottomTabNavigator.tsx` because generics imported from `@react-navigation/native` expects different params.

**Comment by okwasniewski** [comment]
Hey, `@bottom-tabs/react-navigation` dropped support for React Navigation v6 in 0.7.0 (https://github.com/okwasniewski/react-native-bottom-tabs/releases/tag/react-native-bottom-tabs%400.7.0)

But you can still use `@bottom-tabs/react-navigation@0.6.0` with the newest version of `react-native-bottom-tabs` (to continue receiving new features)
