### ISSUE TITLE
Document minimum deployment target

### ISSUE THREAD

**Issue by gorbypark** [okwasniewski/react-native-bottom-tabs#18]
`npx expo prebuild --clean` fails with `Specs satisfying the 'react-native-bottom-tabs (from '../node_modules/react-native-bottom-tabs')' dependency were found, but they required a higher minimum deployment target.`.

Seems like the pod spec is `s.platforms    = { :ios => "14.0", :visionos => "1.0" }`

Fix for Expo/iOS:
```
{
  "expo": {
    "plugins": [
      [
        "expo-build-properties",
        {
          "ios": {
            "deploymentTarget": "14.0"
          }
        }
      ]
    ],
  }
}
```

Does Android require more than SDK34?

- [ ] Document minimums required for each platform
- [ ] Document how to set minimums in react native (bare) iOS
- [ ] Document how to set minimums in react native (bare) Android
- [x] Document how to set minimums in Expo iOS
- [ ] Document how to set minimums in Expo Android
- [ ] Update README

**Comment by okwasniewski** [comment]
Hey, thanks for opening the issue. README has been updated in #17

For Android this lib requires `minSdkVersion` set to 21 or higher.
