### ISSUE TITLE
Overlay Unimplemented component <RNCTabView> on ios.

### ISSUE THREAD

**Issue by a-eid** [okwasniewski/react-native-bottom-tabs#182]
### Before submitting a new issue

- [x] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

getting this overlay on IOS

![simulator_screenshot_BC32E77A-968C-41F0-811B-15DC01F440E9](https://github.com/user-attachments/assets/39c0697a-458d-4b2d-b7fb-7ba44af970ef)

### Library version

0.7.3

### Environment info

```shell
npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 15.1.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 174.39 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.18.1
    path: ~/n/bin/node
  Yarn:
    version: 1.22.22
    path: ~/n/bin/yarn
  npm:
    version: 10.8.2
    path: ~/n/bin/npm
  Watchman:
    version: 2024.09.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /Users/ahmedelshentenawy/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.7
    path: /Users/ahmedelshentenawy/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 16.0.0
    wanted: latest
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

➜  tabbar-repro git:(main) ✗ npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 15.1.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 88.00 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.18.1
    path: ~/n/bin/node
  Yarn:
    version: 1.22.22
    path: ~/n/bin/yarn
  npm:
    version: 10.8.2
    path: ~/n/bin/npm
  Watchman:
    version: 2024.09.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /Users/ahmedelshentenawy/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.7
    path: /Users/ahmedelshentenawy/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 16.0.0
    wanted: latest
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

1. installing package
2. build new dev client
3. try to use the package

### Reproducible sample code

```js
[repro](https://github.com/a-eid/bottom-tabs-repro)
```

**Comment by a-eid** [comment]
it looks like `react-native-bottom-tabs` pod is never installed.

**Comment by a-eid** [comment]
adding "react-native-bottom-tabs" as a deps and I am no longer able to install pods 


<img width="1512" alt="Screenshot 2024-12-06 at 3 28 31 PM" src="https://github.com/user-attachments/assets/b89bd4b5-db7c-4742-bcad-4064aa140e87">

**Comment by okwasniewski** [comment]
Hey, did you follow installation instructions to enable static frameworks?

https://okwasniewski.github.io/react-native-bottom-tabs/docs/getting-started/quick-start.html

**Comment by a-eid** [comment]
> Hey, did you follow installation instructions to enable static frameworks?
> 
> [okwasniewski.github.io/react-native-bottom-tabs/docs/getting-started/quick-start.html](https://okwasniewski.github.io/react-native-bottom-tabs/docs/getting-started/quick-start.html)


yes, installing fixes the issue. both the pods issue and the original issue in general.  

```json
	"@bottom-tabs/react-navigation": "0.7.0",
	"react-native-bottom-tabs": "0.7.0",
    "expo-image": "2.0.3",
```

**Comment by okwasniewski** [comment]
Thanks for checking, looks like we can close it

**Comment by a-eid** [comment]
@okwasniewski shouldn't installing `expo-image` be optional ? 
also I don't think it's very clear in the docs that you need to install both `	"@bottom-tabs/react-navigation"` & `"react-native-bottom-tabs"`

**Comment by okwasniewski** [comment]
It's optional, you just need to enable static frameworks. Installing expo image fixes it because expo image uses same dependencies as bottom tabs and they fix it in their autolinking (but only for expo modules). 

Thanks for the feedback I will look into this, PRs are welcome 🙏

**Comment by okwasniewski** [comment]
@ImmanuelKannan So are you doing Expo prebuild? 

npx expo prebuild --clean 

And then npx expo ios

If you use expo go you might end up getting this issue

**Comment by ImmanuelKannan** [comment]
@okwasniewski thank you so much! You're right, that bit about it not working on Expo Go was there in the docs. Thanks a lot, TIL about Prebuild!

**Comment by vinumzz** [comment]
Im getting the same error even after running prebuild, deleting ios and android folder and clean cache builds. Multiple times. I have no idea whats causing it
