### ISSUE TITLE
Hide a screen from the tab bar

### ISSUE THREAD

**Issue by rochajulian** [okwasniewski/react-native-bottom-tabs#203]
### Why it is needed?

I used to use Expo's built in Tabs and for any route that I did not want displayed in the tab bar I would simply use `href: null` and `tabBarStyle: { display: "none" }`. I can't seem to do that anymore with this library. 

This is needed because sometimes I don't want every screen from my `(tabs)` group to be displayed in the tab bar.

### Possible implementation

Perhaps you guys could simplify Expo's solution and imply create a prop like `screenHidden`? Or if that's not possible, just copy Expo's solution like I've shown below. 

### Code sample

```js
const TabLayout = () => {
  return (
    <Tabs
      backBehavior="history"
      screenOptions={{
        tabBarActiveTintColor: Colors.primary.base,
        tabBarInactiveTintColor: Colors.ink.lighter,
      }}
    >
      <Tabs.Screen
        name="profile"
        options={{
          href: null,
          tabBarStyle: {
            display: "none"
          }
        }}
      />
      <Tabs.Screen
        name="settings"
        options={{
          tabBarLabel: "Settings",
          tabBarIcon: ({ color, size }) => (
            <Ionicons name="settings-outline" color={color} size={size} />
          )
        }}
      />
    </Tabs>
  );
};

export default TabLayout;
```
```

**Comment by okwasniewski** [comment]
Hey you can use `tabBarItemHidden` to hide items from showing in the tab bar

**Comment by rochajulian** [comment]
> Hey you can use `tabBarItemHidden` to hide items from showing in the tab bar

Hey, i did see that prop earlier but i'm unsure where it goes as there's no examples online or code completion on my end. Do you happen to know?

**Comment by okwasniewski** [comment]
You need to pass it to screenOptions of each screen you want to hide. 

Here are the docs: https://okwasniewski.github.io/react-native-bottom-tabs/docs/guides/usage-with-react-navigation.html#tabbaritemhidden

You should have correct auto completion if you use compatible version of React Navigation (v7)
