### ISSUE TITLE
sfSymbol in react-native-bottom-tabs always displays as fill

### ISSUE THREAD

**Issue by kanapan** [okwasniewski/react-native-bottom-tabs#216]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

I encountered an issue where the sfSymbol in the native-bottom-tab component always displays as a filled icon, rather than as an outline as expected.

### Library version

0.7.6

### Environment info

```shell
System:
  OS: macOS 15.3
  CPU: (8) arm64 Apple M3
  Memory: 119.64 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: ~/.nvm/versions/node/v20.11.1/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 16.2/16C5023f
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 23.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0
    wanted: 15.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.5
    wanted: 0.76.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Steps to reproduce

create tab 

<img width="627" alt="image" src="https://github.com/user-attachments/assets/8631a1e6-d4b6-4a33-947b-b7beb110726e" />

### Reproducible sample code

```js
import HomeNavigator from './tab/home-navigator';
import type React from 'react';
import { createNativeBottomTabNavigator } from '@bottom-tabs/react-navigation';

const Tab = createNativeBottomTabNavigator();

const TabNavigator = (): React.ReactElement => {
  return (
    <Tab.Navigator>
      <Tab.Screen
        name="HomeNavigator"
        component={HomeNavigator}
        options={{
          tabBarLabel: 'Home',
          tabBarIcon: () => ({ sfSymbol: 'house' }),
        }}
      />
      <Tab.Screen
        name="HomeFillNavigator1"
        component={HomeNavigator}
        options={{
          tabBarLabel: 'Home Fill',
          tabBarIcon: () => ({ sfSymbol: 'house.fill' }),
        }}
      />
    </Tab.Navigator>
  );
};

export default TabNavigator;
```

display correct
```
import { SFSymbol } from 'react-native-sfsymbols';

  <SFSymbol
        name="house"
        size={16}
        resizeMode="center"
        color={'white'}
        style={{ width: 32, height: 32, marginTop: 384, marginLeft: 16 }}
      />
```

**Comment by okwasniewski** [comment]
Hey! Thanks for opening the issue. 

Can you check if this also happens on iOS? I will check a native visionOS App because Im not sure whether this is a limitation of visionOS to have always filled icons

**Comment by kanapan** [comment]
@okwasniewski I just tested it on iOS, and it works perfectly fine there. 

<img width="356" alt="image" src="https://github.com/user-attachments/assets/a789b286-4f54-4527-b202-9bcef482bed2" />

**Comment by okwasniewski** [comment]
@kanapan I've tested it in both bottom tabs and my Native SwiftUI App and no matter what I do it's always filled. So it's probably something with visionOS that doesn't allow for non filled variants

![CleanShot 2024-12-18 at 16 43 22@2x](https://github.com/user-attachments/assets/0b1361a1-2414-4f11-ad6b-5706ce925407)

**Comment by okwasniewski** [comment]
I'm closing this since there is nothing we can do about it, sorry!
