### ISSUE TITLE
ReactNode icons not supported, even though types specify you should use them

### ISSUE THREAD

**Issue by fredrikburmester** [okwasniewski/react-native-bottom-tabs#27]
Using a ReactNode as icon gives me this error:

![simulator_screenshot_EE21B19E-6E29-4BF0-8D51-952AD66CF549](https://github.com/user-attachments/assets/d4191b6a-45f3-4985-bfce-72ea9b3b339d)

<img width="826" alt="Screenshot 2024-10-09 at 19 58 40" src="https://github.com/user-attachments/assets/277f6c61-6f41-406d-a3fc-04238e109e32">

Here's my code:
```
<NativeTabs.Screen
        name="(home)"
        options={{
          title: "Home",
          tabBarIcon: ({ focused, color, size }) => (
            <Ionicons name="home" size={size} color={color} />
          ),
        }}
      />
```

**Comment by okwasniewski** [comment]
Hey! 

Thanks for opening the issue.

I've looked at your PR: https://github.com/fredrikburmester/streamyfin/pull/166/files

It looks like you are importing `BottomTabNavigationOptions` 

```ts
import { BottomTabNavigationOptions } from "@react-navigation/bottom-tabs"; 
```

You should import

```ts
import { NativeBottomTabNavigationOptions } from "react-native-bottom-tabs/react-navigation"
```

This will give you correct typings. You can't pass ReactNode for the icon. 

If you want to use react-native-vector-icons you can use `getImageSourceSync` from `react-native-vector-icons`: 

```
import Icon from 'react-native-vector-icons/Ionicons';

const navIcon = Icon.getImageSourceSync('md-arrow-back', 24, 'white');
```

**Comment by fredrikburmester** [comment]
Ah, thank you for the amazing support!
