### ISSUE TITLE
Blur is not calculated/cleared before screen focus?

### ISSUE THREAD

**Issue by fredrikburmester** [okwasniewski/react-native-bottom-tabs#35]
The pink from the home screen is visible on the search page for a split second.

https://github.com/user-attachments/assets/22171c59-2dc9-4eda-85b4-98d962636ded

**Comment by okwasniewski** [comment]
Hey, can you check if this occurs when you turn off lazy loading? 

I wonder if this appears in native apps

**Comment by fredrikburmester** [comment]
Doesn't seem to matter if i use lazy or not. @okwasniewski

**Comment by fredrikburmester** [comment]
Thank you for all work that has been done on this library. Any updates on this issue?

https://github.com/user-attachments/assets/a19fc1aa-6ad9-436a-9fd3-e4f5b5f2b6cc

**Comment by okwasniewski** [comment]
> Thank you for all work that has been done on this library. Any updates on this issue?
> 
> 
> 
> https://github.com/user-attachments/assets/a19fc1aa-6ad9-436a-9fd3-e4f5b5f2b6cc
> 
> 


I'll look into it this week, can you check if this blur calculation issue is also appearing when you disable animations? `disablePageAnimations` prop

Also does it appear on the tab bar blur or only header?

I've tested it on SwiftUI app and it didn't happen so it must be something with the integration

**Comment by fredrikburmester** [comment]
It's working fine in the tab bar. 
https://github.com/user-attachments/assets/dc77673f-4887-486f-bda1-2c367295db4e

**Comment by okwasniewski** [comment]
Hey @fredrikburmester,

I've recreated the same scenario in the native SwiftUI App, and the behavior looks the same.

https://github.com/user-attachments/assets/9ab10088-8965-4da5-ac19-2381bb68f791

Unfortunately, in this case, there is not much we can do about it, I would suggest using `disablePageAnimations={true}`.

**Comment by fredrikburmester** [comment]
In the video where i show the tab bar blur, it seems to work (for the tab bar), but in your latest video it doesn't. Why could that be?

**Comment by okwasniewski** [comment]
Maybe because you are switching between tabs with blur and without blur, in my native app demo I'm switching between both tabs that need to blur(?), it looks like this animation messes up blur calculations but there is nothing we can do about it.. This can be reported as a bug in SwiftUI to Apple

**Comment by okwasniewski** [comment]
@fredrikburmester You can even see this bug appearing in Apple Podcasts app 😅


https://github.com/user-attachments/assets/dd9130f4-5b85-4d9d-9a1f-32424cf37602

**Comment by fredrikburmester** [comment]
Oh wow that's crazy... 😆
