### ISSUE TITLE
Fix custom icon aspect ratio

### ISSUE THREAD

**Issue by fredrikburmester** [okwasniewski/react-native-bottom-tabs#39]
See difference between sfSymbol and PNG image of same icon. It's very clear when looking at a real device.

<img width="184" alt="Screenshot 2024-10-13 at 13 28 43" src="https://github.com/user-attachments/assets/c17c94e4-bc5a-42da-a84d-53d89e5a2c69">

_PNG Icon is rendered at point size 200 with pixel size 10x._

The icon is also rendered incorrectly (too large)

<img width="75" alt="Screenshot 2024-10-13 at 13 36 04" src="https://github.com/user-attachments/assets/3f163607-2574-44e9-9c6b-f9d377e6f94b">

My code 

```
tabBarIcon: ({ color, focused, size }) =>
            require("@/assets/icons/magnifyingglass.png"),
```

**Comment by okwasniewski** [comment]
Hey, thanks for opening the issue.

Does it also occur on Android?

**Comment by fredrikburmester** [comment]
I'm having a hard time testing Android, see my other issue.

**Comment by okwasniewski** [comment]
Hey, the issue with low resolution should be fixed in 0.0.10 let me know if it works for you 😄

**Comment by fredrikburmester** [comment]
They are no longer rendered in a low resolution but the aspect ration is not correct. 

<img width="456" alt="Screenshot 2024-10-16 at 14 11 47" src="https://github.com/user-attachments/assets/9681221d-63cf-4547-966d-46cdc1e0e8ac">

Comparison to original SF icon:

<img width="116" alt="Screenshot 2024-10-16 at 14 12 05" src="https://github.com/user-attachments/assets/e78915d2-23a5-430a-81bf-1bfd6a3fe353">

**Comment by okwasniewski** [comment]
Thanks for checking it out @fredrikburmester, changed issue title to add this as a new feature, currently the icon size is a constant. We should either allow for specifying icon size or fix the aspect ratio
