### ISSUE TITLE
Tab bar looks strange on Android (dark mode?)

### ISSUE THREAD

**Issue by fredrikburmester** [okwasniewski/react-native-bottom-tabs#40]
<img width="520" alt="Screenshot 2024-10-13 at 13 43 10" src="https://github.com/user-attachments/assets/ea868d64-aa46-4036-bd0a-a891d9d9d422">

Code:
```
<NativeTabs.Screen
        name="(libraries)"
        options={{
          title: "Library",
          tabBarIcon: ({ color, focused, size }) =>
            require("@/assets/icons/server.rack.png"),
        }}
      />
```

**Comment by okwasniewski** [comment]
Hey, thanks for opening the issue.

This is indeed an issue with dark mode. The styles of the TabBar on Android are dictated by `styles.xml` file (Native project file).

We will probably need Expo Config plugin to allow for easy changes. Have you modified this file in any way? Also  is the TabBar white if you switch to white mode?

**Comment by fredrikburmester** [comment]
I have not modified the styles.xml at all. Would be great with an Expo config plugin. 

I will test changing to light mode later today and report back.

**Comment by fredrikburmester** [comment]
I found that changing color props did nothing. Have not had time to test light mode yet.

**Comment by okwasniewski** [comment]
> @okwasniewski there is no way to pass colors as props ?

Not at the moment, this issue #11 is tracking the progress

**Comment by okwasniewski** [comment]
Issue tracking expo config plugin: #48
