### ISSUE TITLE
Disable default animation on iOS

### ISSUE THREAD

**Issue by ferrannp** [okwasniewski/react-native-bottom-tabs#45]
Thew fade animation is nice but a lot of apps go with no animation. Would be nice to have a prop to disable it if possible!

**Comment by okwasniewski** [comment]
Released in 0.0.11 🚀

**Comment by gunnartorfis** [comment]
@okwasniewski didn't want to open up a new issue, but my tabs screens don't seem to be animating on iOS.
Is there some config/setting I need to apply in order to enable it?

**Comment by okwasniewski** [comment]
> @okwasniewski didn't want to open up a new issue, but my tabs screens don't seem to be animating on iOS.
> 
> Is there some config/setting I need to apply in order to enable it? 

@gunnartorfis the animation is very subtle, you can disable it to see how it looks by passing disablePageAnimations to the navigator.

What version of the OS are you testing on?

**Comment by gunnartorfis** [comment]
Don't tell me it's iOS 18 only? If so, sorry for the tag 😬

**Comment by okwasniewski** [comment]
> Don't tell me it's iOS 18 only? If so, sorry for the tag 😬 

No worries! From my quick research it looks like it's iOS 18 + 😅
