### ISSUE TITLE
Support long press

### ISSUE THREAD

**Issue by okwasniewski** [okwasniewski/react-native-bottom-tabs#58]
Goal of this issue is to implement long press support for both Android and iOS.

**Comment by shubhamguptadream11** [comment]
Hey @okwasniewski ,
I’ve implemented long press support on Android first. Could you please take a look at the approach and API in this [PR](https://github.com/okwasniewski/react-native-bottom-tabs/pull/66)? Once you’ve reviewed it, I’ll proceed with implementing the same for iOS if everything looks good to you.

Looking forward to your feedback!

**Comment by okwasniewski** [comment]
Thanks to @shubhamguptadream11 for implementing this!
