### ISSUE TITLE
Implement `preventDefault` for events

### ISSUE THREAD

**Issue by okwasniewski** [okwasniewski/react-native-bottom-tabs#73]
Goal of this PR is to allow users to prevent default on the react navigation events. 

```ts
React.useEffect(() => {
  const unsubscribe = navigation.addListener('tabPress', (e) => {
    // Prevent default behavior
    e.preventDefault();

    // Do something manually
    // ...
  });

  return unsubscribe;
}, [navigation]);
```

**Comment by a-eid** [comment]
also for listeners props, we often dos something similar to this 


<img width="613" alt="Screenshot 2024-10-31 at 6 51 20 PM" src="https://github.com/user-attachments/assets/02c5cfb0-0363-4f28-91a9-6235a95ce9bf">

**Comment by okwasniewski** [comment]
Good news! 

I've manged to get it working on iOS 🎉 cc: @gunnartorfis

https://github.com/user-attachments/assets/2c153f8d-28f1-4657-95ca-2c006ffa81a0

**Comment by gunnartorfis** [comment]
🔥🔥
