### ISSUE TITLE
Android TV support

### ISSUE THREAD

**Issue by douglowder** [okwasniewski/react-native-bottom-tabs#81]
Will be working on this now that Apple TV seems to be in good shape.

With Fabric off, currently seeing the error below.

![Screenshot_1730055944](https://github.com/user-attachments/assets/0f124825-7205-4a8f-a4f3-434f81716be9)

**Comment by douglowder** [comment]
Hi @okwasniewski !

I updated to latest main, and modified the example to use `npm:react-native-tvos@0.75.4` for the RN dependency. The example seems to run just fine on Android TV emulator.

I suspect the errors I am seeing with my projects are due to changes that have happened in RN 0.76 (I'm testing with Expo SDK 52 beta). The errors are happening in Android mobile too, so they are not TV-specific.

Closing this issue as resolved.

**Comment by okwasniewski** [comment]
Nice! @douglowder would you mind posting a screenshot of how it looks? Might be useful for the docs 👍🏻

**Comment by douglowder** [comment]
Here's a video -- changed activeOpacity to 0.7 on the home screen buttons but otherwise no changes in example source.


https://github.com/user-attachments/assets/7cd67267-033b-473d-a71f-f118966a4551

**Comment by douglowder** [comment]
Seeing some weird behavior with the latest code (version 0.2.0) on Android TV with Expo Router, SDK 52 beta, new arch enabled. Labels are only rendered when active, it seems. Reopening this issue to investigate the problem.

https://github.com/user-attachments/assets/44992fbe-c093-4563-928e-a56af2772c4a

**Comment by okwasniewski** [comment]
@douglowder It's native behavior you can pass labeled={false} and it will show all labels. Are the icons rendering properly?

**Comment by douglowder** [comment]
Thanks that works! Icons also work!

**Comment by okwasniewski** [comment]
Awesome, so I think this can be closed, thanks for checking it
