### ISSUE TITLE
The library doesn't support edge-to-edge

### ISSUE THREAD

**Issue by zoontek** [okwasniewski/react-native-bottom-tabs#97]
Hello again! 🏓

I have a bad news, `react-native-edge-to-edge` is not at fault at all 😬

Having extra themes will be a nice touch to avoid the initial system bars blink (which is only visible if there's no splash screen, as [applyEdgeToEdge](https://github.com/zoontek/react-native-edge-to-edge/blob/f14c13ebf014dce32609e215f603075f00263855/android/src/main/java/com/zoontek/rnedgetoedge/EdgeToEdgeModuleImpl.kt#L23) will probably be called before you app can switch from your `BootTheme` to `AppTheme`)

To reproduce, I used a blank app with `react-native-bottom-tabs@0.2.0`, as I was not able to quickly understand where are the `styles.xml` and `MainActivity.kt` on this repository example app 😅
I didn't installed `react-native-edge-to-edge` as I want to reproduction to be as small as possible.

It breaks immediately when I set `WindowCompat.setDecorFitsSystemWindows(window, false)`. That's the first step of [how to enable edge-to-edge](https://developer.android.com/develop/ui/views/layout/edge-to-edge-manually).

This is of course used by `react-native-edge-to-edge`, but also by:
- [react-native-keyboard-controller](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/1.14.3/android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt#L128)
- [react-native-unistyles](https://github.com/jpudysz/react-native-unistyles/blob/v2.11.0/android/src/main/java/com/unistyles/UnistylesModule.kt#L127)
- [react-native-screens](https://github.com/software-mansion/react-native-screens/blob/3.35.0/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt#L220) 

And probably a lot of other libs.

The reproduction can be found [here](https://github.com/zoontek/rn-bottom-bars-issue). And [these changes](https://github.com/zoontek/rn-bottom-bars-issue/commit/c97fcd271985d2a2d032d5f8e1f3289056dbc613) are enough to recreate the issue.

<img width="1554" alt="Screenshot 2024-10-30 at 18 33 12" src="https://github.com/user-attachments/assets/4ec51ab9-f6f9-4e1d-b41f-cb36d7386a9e">

**Comment by okwasniewski** [comment]
@zoontek Thanks for your investigation! I will handle it in the library 🙌

**Comment by okwasniewski** [comment]
I got this to work! 

@zoontek As you are more familiar with the topic, what's a reliable way of checking if edge to edge is enabled? It's the last thing Im struggling with 

![CleanShot 2024-10-30 at 22 06 19@2x](https://github.com/user-attachments/assets/7e9acefb-2835-470e-a05f-c9ffa6d2a9d7)

**Comment by zoontek** [comment]
@okwasniewski As I mentionned in [this message](https://github.com/software-mansion/react-native-screens/pull/2464#issuecomment-2446531882), there's no way to properly detect edge-to-edge (see [this tweet too](https://twitter.com/jpudysz/status/1850507484219232545)).
That's why we went for a common library, because at least this is something that could be detected.

Are you performing different computation if it's enabled or not (maybe you can inset in all cases, as it's 0 when disabled)?

If yes, add [`react-native-is-edge-to-edge`](https://github.com/zoontek/react-native-edge-to-edge/tree/main/react-native-is-edge-to-edge) as a dependency (it's extra lightweight), potentially add a prop / option (`navigationBarTranslucent`, for example).

Then follow the method in the README:

```jsx
import { controlEdgeToEdgeValues, isEdgeToEdge } from "react-native-is-edge-to-edge";

const EDGE_TO_EDGE = isEdgeToEdge();

function TabBar({ navigationBarTranslucent = false }) {
  if (__DEV__) {
    controlEdgeToEdgeValues({ navigationBarTranslucent });
  }

  return (
    <NativeTabBar
      navigationBarTranslucent={EDGE_TO_EDGE || navigationBarTranslucent}
      // …
    />
  );
}
```

This way, it will "just work" for people using `react-native-edge-to-edge`, and the others will still be able to set `navigationBarTranslucent={true}` if they want.

**Comment by okwasniewski** [comment]
Thanks for the tip! 

Looks like this check on the native side `val isSystemBarTransparent = window?.navigationBarColor == Color.TRANSPARENT` might be enough for this library as I need to "stretch" the navigation view only when the navigationBarColor is transparent.

I've tested it with your library (enabled and disabled) and this PR: #101 should address this issue.

**Comment by zoontek** [comment]
@okwasniewski This is really fragile. On Android < 10, `window?.navigationBarColor != Color.TRANSPARENT`, even in edge-to-edge (it's a semi opaque white or black, depending on the OS versions)

Even on newer versions, buttons based navigation isn't transparent:

<img width="930" alt="Screenshot 2024-10-31 at 00 00 48" src="https://github.com/user-attachments/assets/676d6b4b-bbca-4c38-b193-495ac330597d">

**Comment by zoontek** [comment]
Note that if you don't want an extra JS dependency, you can achieve package detection in Kotlin too:

```kt
val isSystemBarTransparent = try {
  Class.forName("com.zoontek.rnedgetoedge.EdgeToEdgePackage")
  true
} catch (exception: ClassNotFoundException) {
  window?.navigationBarColor == Color.TRANSPARENT // fallback to best-effort detection
}
```

**Comment by okwasniewski** [comment]
Thanks @zoontek this check in Kotlin is perfect! 

Going to add it 👍🏻

**Comment by okwasniewski** [comment]
Thanks for your support @zoontek I also added page in docs describing to install your library in order to enable the support; https://okwasniewski.github.io/react-native-bottom-tabs/docs/guides/edge-to-edge-support.html
